version: '3.8'
services:
  postService-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: postService_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    ports:
      - "3308:3306"

  reviewService-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reviewService_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    ports:
      - "3309:3306"

  commentService-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: commentService_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    ports:
      - "3310:3306"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    container_name: rabbitmq-container