server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - DedupeResponseHeader=Access-Control-Allow-Methods
        - DedupeResponseHeader=Access-Control-Allow-Headers
        - DedupeResponseHeader=Access-Control-Allow-Credentials
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://127.0.0.1:4200, http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/post/**
          filters:
            - RewritePath=/api/post/(?<path>.*), /$\{path}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**
          filters:
            - RewritePath=/api/review/(?<path>.*), /$\{path}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**
          filters:
            - RewritePath=/api/comment/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/